### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by yfinegold** [12rambau/planet-order#15]
Is this app working? I am not able to download the quads and there are no informative error messages.
The dates for the basemaps don't match the actual availability of the basemaps, that is probably one of the issues.

Also the text 'I have plenty of room for explainations' should be removed.

**Comment by 12rambau** [comment]
I'll take only care of the "not working" issue here. I opened another one for the main page explanation paragraph (as a reminder).

## test

I've just tested the module with the NCFI contract planet key that I have on the Congo, Brazaville area (administrative level 1). 
The grid was generated, the basemap was displayed as shown on this screenshot:

![Capture d’écran 2021-04-21 à 18 58 54](https://user-images.githubusercontent.com/12596392/115592833-0aa0aa00-a2d4-11eb-872d-67a1bbb1d7b5.png)

after clicking on the download btn I was able to fetch all the files in my file manager:

![Capture d’écran 2021-04-21 à 18 59 25](https://user-images.githubusercontent.com/12596392/115592917-22782e00-a2d4-11eb-9a7d-0647b9c244b6.png)

## question 

Can you elaborate on: 
> The dates for the basemaps don't match the actual availability of the basemaps

These basemaps are retrieved from the available maps associated to your key. how can you tell that the basemap doesn't fit ? 

I realized recently that the Planet API client is limited too 50 results per pages, I opened a PR to add a page param (https://github.com/planetlabs/planet-client-python/pull/273)

Normally if no images are available, I'm just skipping and jumping to the next one, maybe I should add a message....

**Comment by 12rambau** [comment]
## update 

I changed the module structure when you try to download images 3 cases are counted : 
- **down**: the image is effectively downloaded
- **skip**: the image is was already in SEPAL
- **fail**: the image was not found

At the end of the download the tool gives a sum up of the downloading process:
- **red** less than 20% were availabe, 
- **orange** less than 50%
- else **green**

On an empty area like corsica I get the following results page:
<img width="309" alt="Capture d’écran 2021-04-22 à 13 11 22" src="https://user-images.githubusercontent.com/12596392/115704943-3cfde600-a36c-11eb-879a-5b21aff85f3b.png">

Can you test it again and tell me what is displayed ? 

PS: I removed the txt from the page and created a documentation page in sepal-doc instead: https://docs.sepal.io/en/latest/modules/dwn/planet_order.html

**Comment by yfinegold** [comment]
![planetlab_order_error1](https://user-images.githubusercontent.com/5813936/116556654-b1380c80-a8cb-11eb-9ea1-8d44f1a6df7d.PNG)
Are you able to see the screenshot I uploaded? I tested in ghana and it still doesn't work. I get the error 'download' and I am not able to visualize the imagery

**Comment by 12rambau** [comment]
Normally you should see the basemap of the global_monthly. I think the problem is coming from here 
Are you 100% sure you are using a Planet NICFI key or at least one that allows download ?

**Comment by yfinegold** [comment]
working!!! my guess is it was an issue with the API key. Thanks Pierrik!!
