### ISSUE TITLE
For some reason this below is printing to screen before the UI opens...

### ISSUE THREAD

**Issue by eriklindquist** [12rambau/planet-order#23]
{'ADMIN0': {'name': 'Country/Province', 'type': 'Administrative definitions'}, 'ADMIN1': {'name': 'Admin level 1', 'type': 'Administrative definitions'}, 'ADMIN2': {'name': 'Admin level 2', 'type': 'Administrative definitions'}, 'SHAPE': {'name': 'Vector file', 'type': 'Custom geometries'}, 'DRAW': {'name': 'Drawn shapes', 'type': 'Custom geometries'}}

**Comment by 12rambau** [comment]
it's a legacy print coming from sepal_ui. it wasn't displayed before but it is now afecting everyone. it' already solved here : https://github.com/12rambau/sepal_ui/commit/ce5226852ee703edfa918c90c27a4d25bf09f288 and will be push to SEPAL in the next release. 

I doesn't affect the apps behavior, just the display

**Comment by eriklindquist** [comment]
cool.

**Comment by eriklindquist** [comment]
As a side note...would whatever is causing this message to print to screen maybe be a way to print 'App Loading' to the screen before it loads? Then somehow 'clear' it before the app starts?
