### ISSUE TITLE
download as a GEE asset

### ISSUE THREAD

**Issue by yfinegold** [12rambau/planet-order#24]
Would be helpful to download the results as a GEE asset to use in the classification workflow in SEPAL

**Comment by 12rambau** [comment]
I cannot write images on the behalf of Google users. That's the main issue with GEE and we discussed it with @cdanielw during the last SEPAL show&tell: 
- Downstream (from EE to SEPAL) is always working 
- Upstream (from SEPAL to EE) is extremely tricky for `FeatureCollection` and impossible for `Image`.

My only hope for this matter is that Planet provide a project (so images would already live in EE) but I don't think that is already the case. Do you happen to have more info on that ?

**Comment by 12rambau** [comment]
Now that the functionality is available in the main SEPAL Framework I would say let's keep Planet order for non-GEE stuff and use the recipe for GEE mosaics
