### ISSUE TITLE
Long wait time when creating a manual aoi

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/planet-order#3]
When creating a manual aoi in the aoi selection tab, the process is taking so long because it's exporting the geometry to GEE (which is not needed in this app), would be nice to have the option to create aoi's without sending them to gee, just json format.

**Comment by 12rambau** [comment]
I'm working on a way to make the aoi_selector more flexible, but that's (as you know) already quite messy ;-)

**Comment by dfguerrerom** [comment]
If you need to refactor it I could help with some ideas (and/or code), just let me know ;)

**Comment by 12rambau** [comment]
solved in sepal_ui v2
